name: fork
on:
  fork

jobs:
  cron:
    name: "Node.js"
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set Env
        run: |
          echo "OWNER_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')" >> $GITHUB_ENV
      - name: Install
        run: yarn install
      - name: Update
        run: npm run main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          OWNER_NAME: ${{ env.OWNER_NAME }}
      - name: Commit
        uses: EndBug/add-and-commit@v6
        with:
          message: "Update Image"
          push: true
